### ISSUE TITLE
如何正确使用 user 方式进行登录？

### ISSUE THREAD

**Issue by mouyong** [binsee/padchat-sdk#10]
在使用 user 方式进行登录的时候。会提示不安全的登录，要求进行安全验证。如何可以跳过这一步。或者如何能让流程继续下去？

**Comment by binsee** [comment]
推荐使用扫码登陆方式。

**Comment by mouyong** [comment]
如果希望二维码在网页上，但是因为程序是在 node 直接执行了。应该怎么做才能通过网页触发程序去连接获取二维码？socket.io 吗
