### ISSUE TITLE
使用wxdata+token登录失败

### ISSUE THREAD

**Issue by keithchi** [binsee/padchat-sdk#16]
代码基本就是你写的那个demo，我第一次使用的时候没有问题，大概几个小时后退出再登录的时候出现了这个问题，然后我试着换新的token，但是还是失败，之后就再也没有成功过。

async function run_wechat(){
    wx
    .on('open', async () => {
        let login_wxdata = await dp.query("select value from back_control where name='wxdata'");
        login_wxdata = login_wxdata[0]['value'];
        let login_token = await dp.query("select value from back_control where name='token'");
        login_token = login_token[0]['value'];
        let ret;
        ret = await wx.init();
        if (!ret.success) {
            console.error('初始化失败! ret:', ret);
            return
        }
        console.log('初始化成功! ret:', ret);
        // ret = await wx.login();
        ret = await wx.login('request',{wxData:login_wxdata,token:login_token});
        if (!ret.success) {
            console.error('请求登录失败! ret:', ret);
            return
        }
        console.log('请求登录成功! ret:', ret);
    })
    .on('qrcode', data => {
        if (data.url) {
            console.log('登陆二维码url: %s ,请扫码登陆：', data.url);
            qrcode.generate(data.url);
            return
        } else if (data.qrCode) {
            console.log('登陆二维码图片数据，请输出到文件扫码。');
            return
        }
        console.error('没有发现二维码数据!')
    })
    .on('scan', data => {
        switch (data.status) {
            case 0:
                console.log('等待扫码...', data);
                break;
            case 1:
                console.log('已扫码，请在手机端确认登陆...', data);
                break;
            case 2:
                switch (data.subStatus) {
                    case 0:
                        console.log('扫码成功！登陆成功！', data);
                        break;
                    case 1:
                        console.log('扫码成功！登陆失败！', data);
                        break;
                    default:
                        console.log('扫码成功！未知状态码！', data);
                        break;
                }
                break;
            case 3:
                console.log('二维码已过期', data);
                break;
            case 4:
                console.log('手机端已取消登陆！', data);
                break;
            default:
                break;
        }
    })
    .on('login', async() => {
        console.log('登陆成功!');
        let get_token = await wx.getLoginToken();
        let sql = "update back_control set value=? where name = 'token'";
        await dp.query(sql,get_token.data.token)
    })
    .on('loaded', () => {
        console.log('载入通讯录完成!')
    })
    .on('push', async(data)=> {
        room_id =  await search_room();
        if(data.mType===1 && data.fromUser === room_id) {
    });

 }

**Comment by binsee** [comment]
你这样贴代码，不利于阅读。

请使用demo代码，来测试自动登陆这个功能。
如果demo也运行异常，请附上`logs/app.log`文件，一定记得先将其中`wxData`和`token`字段进行掩码处理。

**Comment by keithchi** [comment]
demo也失败，额。。node我临时学的，你说的这个日志我没找到

**Comment by binsee** [comment]
你怎么下载的代码？`git clone`还是打包下载？运行后找子目录`logs`

**Comment by keithchi** [comment]
我之前是用 npm i binsee/padchat-sdk  下载的，这里面没有 log4js, demo也是用的说明里面的那份，刚试了下打包下载，用里面的demo没有问题。

**Comment by mouyong** [comment]
@keithchi 通过 npm i 这种方式，是将该项目作为 package 直接使用了。需要你自己将 demo.js 复制到你的项目中，然后，启动 demo.js ，看报错。缺 package 就装，缺文件就去 git 中复制。最后就能生成 logs 目录了

**Comment by binsee** [comment]
近期是否还遇到问题？如果没有的话将关闭此issues
