### ISSUE TITLE
【讨论】是否移除推送扫码登陆的二维码数据

### ISSUE THREAD

**Issue by binsee** [binsee/padchat-sdk#2]
当需要使用扫码登陆时，原始接口返回的是二维码图片数据，尺寸比较大，协议服务程序中已经直接解析为url，并在推送数据中一并推送。
现在有这个url，大尺寸的图片数据可以考虑移除了。

是否有人希望推送中保留原始二维码图片数据？

**Comment by wolf8210137** [comment]
希望移除，直接在终端显示URL生成的二维码

**Comment by binsee** [comment]
二维码内容字段是 `data.url`
二维码图片数据字段是 `data.qrCode`

**Comment by binsee** [comment]
从协议服务程序v1.4.8.248 版本开始，`qrcode`事件推送中移除二维码图片原始数据。

- `data.url` 为登陆二维码内容url
	- nodejs终端可使用`qrcode-terminal`库生成二维码。
	- 也可使用各类api站点、js插件等生成二维码图片，如：`http://qr.liantu.com/api.php?text=${data.url}`

- ~`data.qrCode`~ 登陆二维码图片数据base64文本，已经移除。

```js
const qrcode  = require('qrcode-terminal')

wx.on('qrcode',data=>{
	qrcode.generate(data.url, { small: false })
})
```
