### ISSUE TITLE
[提案] 修改ws通讯荷载数据key名称

### ISSUE THREAD

**Issue by binsee** [binsee/padchat-sdk#28]
### 上行数据：(客户端->服务端)
```js
{
  type: 'user',   //接口类型，目前仅有`user`
  cmd : 'init',   //接口名称
  data:           //荷载数据
  {
    loginType: '',   //接口参数1
    wxData   : '',   //接口参数2
  },
  cmdId: 'b61eb250-3770-11e8-b00f-595f9d4f3df0'  //请求id，用于识别请求与返回其结果
}
```

### 下行数据：（服务端->客户端）
```js
{
  type  : 'cmdRet',                                 //返回数据包类型
  cmdId : 'b61eb250-3770-11e8-b00f-595f9d4f3df0',   //请求id
  taskId: '5',                                      //服务端返回当前实例的任务ID
  data  :                                           //荷载数据（以下字段名称为转换为小驼峰后的，原始数据为下划线分隔）
  {
    error  : '',     //错误提示
    msg    : '',     //其他提示信息
    success: true,   //接口执行是否成功
    data   :         //接口执行结果数据，`push`类型无
    {
      message: '',
      msgId  : '1284778244346771212',
      status : 0
    },
    list:   // 仅`push`类型拥有，包含多个push结构数据
      [
        {
          content    : '信息内容',                  //消息内容或xml结构体内容
          continue   : 1,
          description: '杉木 : 信息内容',             //描述内容
          fromUser   : 'wxid_001',              //发信人
          msgId      : '4032724472820776289',   //消息id
          msgSource  : '',
          msgType    : 5,                       //消息主类型，类型为5时则用子类型判断
          status     : 1,
          subType    : 1,                       //消息子类型
          timestamp  : 1522921008,              //消息时间戳
          toUser     : 'wxid_002',              //收件人
          uin        : 149801234,               //用户uin，全局唯一
          mType      : 1                        //消息类型。等同msgType，当msgType为5时，等同于subType
        }
      ],
  },
}
```

可以看到，下行数据中的荷载数据段名称为`data`，而其下可能会存在`data`和`list`名称的子数据段，分别为接口执行结果数据和推送数组数据。
如果下行数据对象名称为`data`，那么荷载数据就是`data.data`，而接口执行结果为`data.data.data`，推送数据数组为`data.data.list`。
这样很容易令人迷惑，因此希望将荷载数据段名称改为`payload`。

| 上行数据         | 旧名称              | 新名称                 |
| ---------------- | ------------------- | ---------------------- |
| 数据对象         | data                | data                   |
| 荷载数据         | data.data           | data.payload           |
| 接口参数         | data.data.loginType | data.payload.loginType |

| 下行数据         | 旧名称                | 新名称                   |
| ---------------- | --------------------- | ------------------------ |
| 数据对象         | data                  | data                     |
| 荷载数据         | data.data             | data.payload             |
| 接口执行是否成功 | data.data.success     | data.payload.success     |
| 接口执行结果数据 | data.data.data        | data.payload.data        |
| 接口执行结果状态 | data.data.data.status | data.payload.data.status |
| 推送数据         | data.data.list        | data.payload.list        |

**Comment by binsee** [comment]
@fastgoo 请查看后进行回复，谢谢

**Comment by fastgoo** [comment]
没看明白 @binsee

**Comment by fastgoo** [comment]
以前请求参数  
```
{
  type: 'user',   //接口类型，目前仅有`user`
  cmd : 'init',   //接口名称
  data:           //荷载数据
  {
    loginType: '',   //接口参数1
    wxData   : '',   //接口参数2
  },
  cmdId: 'b61eb250-3770-11e8-b00f-595f9d4f3df0'  //请求id，用于识别请求与返回其结果
}
```

现在请求
```
{
  type: 'user',   //接口类型，目前仅有`user`
  cmd : 'init',   //接口名称
  payload:           //荷载数据
  {
    loginType: '',   //接口参数1
    wxData   : '',   //接口参数2
  },
  cmdId: 'b61eb250-3770-11e8-b00f-595f9d4f3df0'  //请求id，用于识别请求与返回其结果
}
```

是这样吗

**Comment by binsee** [comment]
@fastgoo Yes!
关键是下行数据部分要改，因为数据层次太多，容易迷惑人。
虽然sdk框架编写好后基本就不用动了，但这样子感觉不好。

**Comment by ChandlerBent** [comment]
同意。
我刚写sdk的时候，也是有这个的疑惑，后来通过反复测试和查看node sdk才明白原来data是嵌套关系。

**Comment by binsee** [comment]
自 0.6.0版本开始生效
