### ISSUE TITLE
关于服务器地址

### ISSUE THREAD

**Issue by binsee** [binsee/padchat-sdk#34]
当前服务器地址为：`52.80.34.207`，端口为`7777`

后续会改为域名访问

**Comment by binsee** [comment]
服务端增加了负载平衡，现在对外服务端口仅为 `7777`

**Comment by Pengzw** [comment]
请问下这个server 52.80.34.207主要做什么用的?可以用本地127.0.0.1的吗

**Comment by binsee** [comment]
服务端封装了与微信服务器的数据交互，这部分暂时不会开放给本地运行。

**Comment by yue2611032** [comment]
@binsee 您好，我想请问您，socket服务端的源码，可以出售嘛，如果可以的话，请您回复我

**Comment by binsee** [comment]
@yue2611032 不出售，可租用。

**Comment by tangzheng0105** [comment]
我想租用，怎么联系？

**Comment by binsee** [comment]
@tangzheng0105 见 #13  进群说

**Comment by ileadall42** [comment]
我想问一下这个后续是会完全改成租用版本吗?

**Comment by binsee** [comment]
@ileadall42 是的，这个东西也是有成本的。况且一直免费让你用的，你就不怕使用你数据进行盈利吗？

**Comment by binsee** [comment]
测试服务器已经关闭，使用此服务请查看 #13 进群后咨询
