### ISSUE TITLE
Please, provide an english readme

### ISSUE THREAD

**Issue by realtebo** [binsee/padchat-sdk#41]
Your project is very usefull, I'd like to give it a try, but ... i'am not chinese

**Comment by binsee** [comment]
Sorry for my bad english. Since the main users are currently Chinese, only Chinese documents are provided, and it is hoped that others can translate the documents.

**Comment by realtebo** [comment]
I understand, but a lot of not-Chinese people uses wechat now ... not matter why ...  

You're of course not forced to translate to a foreign language. 
I'm simply not able to do it because I don't know Chinese, and even Google don't speak Chinese very well !

Also, I've not enough info to be able to understand what I'm reading, either if it would be in my native language ...

For esample: 

> Description
> Padchat development kit. Log in and operate WeChat through the websocket protocol and the WeChat ipad protocol service program running on the Windows platform.

What is the _"WeChat ipad protocol service program"_ ?

**Comment by binsee** [comment]
WeChat's ipad protocol service program is a WebSocket server program that implements the WeChat iPad communication protocol.
It allows you to operate WeChat via WebSocket communication. Currently this program is not public and only runs on private servers.

**Comment by realtebo** [comment]
Ok... Thanks. This was the interesting part.
