### ISSUE TITLE
接收到修改群公告消息时会触发logout事件导致实例关闭

### ISSUE THREAD

**Issue by lvxuan263** [binsee/padchat-sdk#49]
调用sdk的setRoomAnnouncement接口后，从手机看群公告修改成功，但是程序会立刻触发logout事件，导致程序结束.

cmdRet
```
[2018-08-21T10:27:46.336] [INFO] dev - setRoomAnnouncement ret:
{ success: true, data: { message: '', status: 0 } }
```

补充测试：
    通过sdk登录微信后，手机端直接修改群公告，sdk再接收到任何消息前，触发sdk的logout事件，导致实例关闭并退出。

sdk版本 0.5.10
node版本 10.3.0

**Comment by binsee** [comment]
待解决问题

**Comment by wells1013** [comment]
+1

**Comment by wells1013** [comment]
通过手机 直接设置群公告的时候，也会触发 logout事件，导致程序结束.

**Comment by binsee** [comment]
已经修复
