### ISSUE TITLE
客户端收到“帐号主动登出”消息

### ISSUE THREAD

**Issue by kuifu** [binsee/padchat-sdk#52]
客户端近期经常收到随机性的“帐号主动登出”消息，已经确认，手机一切正常，未做任何主动操作。
请帮忙看下是什么原因，下面日志是2019-09-09的。

```json
{
  "type": "userEvent",
  "event": "logout",
  "taskId": "6FC35489-58D8-BCBA-D8BA-B246EBC9AEAE",
  "data": {
    "msg": "帐号主动登出"
  }
}

{
  "type": "userEvent",
  "event": "over",
  "taskId": "6FC35489-58D8-BCBA-D8BA-B246EBC9AEAE",
  "data": {
    "msg": "账号已登出"
  }
}
###
{
  "type": "userEvent",
  "event": "logout",
  "taskId": "CD854936-A28E-5EE1-D1C0-F3D7A5C7964E",
  "data": {
    "msg": "帐号主动登出"
  }
}

{
  "type": "userEvent",
  "event": "over",
  "taskId": "CD854936-A28E-5EE1-D1C0-F3D7A5C7964E",
  "data": {
    "msg": "账号已登出"
  }
}


```

**Comment by albb52** [comment]
我这边加群会导致这个问题出现

**Comment by kuifu** [comment]
可能是 WX 的安全机制。我手机长时间不用，一旦启动 WX 客户端，机器人就提示账号退出。token 重连就可以。

**Comment by albb52** [comment]
> 可能是 WX 的安全机制。我手机长时间不用，一旦启动 WX 客户端，机器人就提示账号退出。token 重连就可以。
现在还能用吗？我的项目今天连不上服务器了。不知道怎么回事。

**Comment by binsee** [comment]
> > 可能是 WX 的安全机制。我手机长时间不用，一旦启动 WX 客户端，机器人就提示账号退出。token 重连就可以。
> > 现在还能用吗？我的项目今天连不上服务器了。不知道怎么回事。

参考#13

**Comment by kuifu** [comment]
问题复现方法：

1. 手机登录微信 APP
2.机器人启动（扫码）
3.好友邀请微信账号加入群 A
4.手机端点击邀请链接
5.机器人提示`"payload":{"msg":"帐号主动登出"}`

**Comment by kuifu** [comment]
能否尽快实现接口方式接受入群邀请?

否则每加一次群机器人就要退出一次。重登陆后，同时还要再同步一次通讯录（同步完成后，才能收到新的群组变动信息，我目前有1000个联系人或群，同步一次好几十秒）

**Comment by binsee** [comment]
此问题已经修复
