### ISSUE TITLE
二维码登录 提示  扫码成功！未知状态码！

### ISSUE THREAD

**Issue by kevieYu** [binsee/padchat-sdk#53]
扫码成功！未知状态码！ { password: '***hide***',
  status: 2,
  external: '',
  email: '',
  uin: 0,
  deviceType: 'iphone',
  expiredTime: 238,
  headUrl: 'http://wx.qlogo.cn/mmhead/ver_1/ESVRGav6tqH',
  nickName: '哈哈哈哈',
  userName: '123456',
  phoneNumber: '',
  subStatus: -106 }

**Comment by zhengzhejun** [comment]
我也遇到相同问题了，之后收不到任何消息

**Comment by za123** [comment]
相同问题

**Comment by wells1013** [comment]
+1

**Comment by binsee** [comment]
最近一直在处理这个问题，已经找到了临时的解决方案，这几天会进行更新。

**Comment by binsee** [comment]
已经解决。
