### ISSUE TITLE
扫码确认登录过后返回subStatus = -2

### ISSUE THREAD

**Issue by TgolMsk** [binsee/padchat-sdk#56]
如题登陆成功后返回-2下面帖代码
{"type":"userEvent","event":"scan","taskId":"301CD2FF-9C2E-A0F0-88DC-805C7695CEB5","data":{"device_type":"android","expired_time":237,"head_url":"http:\/\/wx.qlogo.cn\/mmhead\/ver_1\/IFexJoZqzvYoL62Vf4J0XLIplzNDNCX1icYmR2xqQ2sk7a2XRcjicuxChpFKqsn22tRib8v5f4iav6GiaRyEYiavT7CNPoAoYMTHawFHfiahfWsll8\/0","nick_name":"aLIEz","password":"***hide***","status":2,"user_name":"wxid_smseowbr61ob22","sub_status":-2,"external":"","email":"","message":"server err!","uin":0,"phone_number":"","long_link_server":"","short_link_server":""}}

**Comment by TgolMsk** [comment]
{"type":"userEvent","event":"scan","taskId":"CB4298CC-81E0-D78D-AB2D-43C8A4DE5BAD","data":{"device_type":"android","expired_time":238,"head_url":"http:\/\/wx.qlogo.cn\/mmhead\/ver_1\/IFexJoZqzvYoL62Vf4J0XLIplzNDNCX1icYmR2xqQ2sk7a2XRcjicuxChpFKqsn22tRib8v5f4iav6GiaRyEYiavT7CNPoAoYMTHawFHfiahfWsll8\/0","nick_name":"aLIEz","password":"***hide***","status":2,"user_name":"wxid_smseowbr61ob22","sub_status":-4,"external":"","email":"","message":"server err!","uin":0,"phone_number":"","long_link_server":"","short_link_server":""}}

**Comment by binsee** [comment]
已经进行修复，请再进行观察。
