### ISSUE TITLE
socket服务器503

### ISSUE THREAD

**Issue by jiqiukun** [binsee/padchat-sdk#59]
今天突然连接socket服务报503，是已经开始用token了吗？还是服务器的问题

**Comment by albb52** [comment]
同问

**Comment by albb52** [comment]
> 今天突然连接socket服务报503，是已经开始用token了吗？还是服务器的问题

你的好了没？我的还不行

**Comment by binsee** [comment]
测试服务器已关，见 #13 进群咨询

**Comment by binsee** [comment]
测试服务器已关，见 #13 进群咨询
