### ISSUE TITLE
【分享】让padchat能直接在terminal终端扫码登录

### ISSUE THREAD

**Issue by wolf8210137** [binsee/padchat-sdk#6]
默认的demo.js，是把登录扫码用的二维码保存到目录下，需要手动打开图片再扫码、确认后才行。
这里做一些小小改动，可以直接在cmd, putty, xshell等终端上直接显示二维码。

1、安装qrcode-terminal模块：
$ npm install qrcode-terminal

2、在demo.js头部引入：
const qrcode = require('qrcode-terminal')

3、把原demo.js中这两行注释掉：
fs.writeFileSync('./qrcode.jpg', Buffer.from(data.qrCode || '', 'base64'))
logger.info('登陆二维码已经写入到 ./qrcode.jpg，请打开扫码登陆！')

4、在这两行的地方直接加上：
	qrcode.generate(data.url || '',  {small: false} , function (qrcode) {
		console.log(qrcode+'\n\n请扫码登录\n');
	});

这样就可以了，刚才测试成功，再运行
$node demo.js
会看到类似这样的图，手机打开扫一扫即可：
![2018040916132089738](https://user-images.githubusercontent.com/17350104/38501874-90a90208-3c40-11e8-8b15-33ab9bcd5e8b.png)

**Comment by binsee** [comment]
good!
