### ISSUE TITLE
调用sendImage接口发送图片失败

### ISSUE THREAD

**Issue by zhangzheng521** [binsee/padchat-sdk#61]
我发的图片大小为64.947 KB啊，每次都没发成功，不知道什么原因
![image](https://user-images.githubusercontent.com/37147722/47283564-7d9f0c00-d616-11e8-99e6-ca28814571a0.png)
这是我发的base64图片格式
![image](https://user-images.githubusercontent.com/37147722/47283587-8f80af00-d616-11e8-8f2a-d1db581dafc9.png)

**Comment by binsee** [comment]
重复问题 #62
