### ISSUE TITLE
quitRoom()退群功能无效

### ISSUE THREAD

**Issue by kuifu** [binsee/padchat-sdk#64]
[WARN][2018-10-28 22:21:54]:Unkown cmdRet:{'type': 'cmdRet', 'cmdId': '18111811', 'taskId': 'FF5DF61C-6D65-A644-C881-A2FFFDCE7C7F', 'data': {'success': True, 'data': {'message': '', 'status': 0}}} - cmdRet

实际，并没有完成退群。

**Comment by leebo** [comment]
退群我也遇到过 有一些无法正常退出情况

**Comment by binsee** [comment]
经测试，此功能正常。

可新建一个群，然后在群内发言，使用quitRoom退出此群，会观察到退出。
