### ISSUE TITLE
建群出现错误

### ISSUE THREAD

**Issue by leebo** [binsee/padchat-sdk#67]
建立第一个群没有问题 建立第二个群的时候 提示
任务出现错误: 服务器返回错误提示：接收推送信息异常！
任务出现错误: 服务器返回错误提示：接收推送信息异常！
任务出现错误: 服务器返回错误提示：接收推送信息异常！
请问这个是怎么回事

**Comment by leebo** [comment]
具体错误信息
通讯录同步完毕！
第一个群.可以建成功
^@{ success: true,
  data:
   { message: 'Everything is OK',
     status: 0,
     userName: '4775668506@chatroom' } }
创建完毕
从这开始建立失败
任务出现错误: 服务器返回错误提示：接收推送信息异常！
任务出现错误: 服务器返回错误提示：接收推送信息异常！
任务出现错误: 服务器返回错误提示：接收推送信息异常！

**Comment by leebo** [comment]
`'use strict'

const Padchat = require('padchat-sdk')
const fs      = require('fs')
const util    = require('util')
const delay    = require('delay')
const qrcode  = require('qrcode-terminal')

/**
* 创建日志目录
*/

try {
  require('fs').mkdirSync('./logs')
} catch (e) {
  if (e.code !== 'EEXIST') {
    console.error('Could not set up log directory, error: ', e)
    process.exit(1)
  }
}

let userCount = 0
let userList = []

const autoData = {
  wxData: '',
  token : '',
}
try {
  const tmpBuf          = fs.readFileSync('./config.json')
  const data            = JSON.parse(String(tmpBuf))
        autoData.wxData = data.wxData
        autoData.token  = data.token
  console.log('载入设备参数与自动登陆数据：%o ', autoData)
} catch (e) {
  console.log('没有在本地发现设备登录参数或解析数据失败！如首次登录请忽略！')
}

let server = 'ws://padchat-sdk.botorange.com:8988/token'

const wx = new Padchat(server)
console.log('当前连接接口服务器为：', server)
let disconnectCount = 0      // 断开计数
let connected       = false  // 成功连接标志

wx
  .on('close', (code, msg) => {
    // 需要注意关闭代码为3201-3203的错误，重连也用，具体参考文档中`close`事件说明
    if (code > 3200) {
      console.log(`Websocket已关闭！code: ${code} - ${msg}`)
      return
    }
    console.log(`Websocket已关闭！code: ${code} - ${msg}`)
    // 根据是否成功连接过判断本次是未能连接成功还是与服务器连接中断
    if (connected) {
      connected = false
      disconnectCount++
      console.log(`第 ${disconnectCount} 次与服务器连接断开！现在将重试连接服务器。`)
    } else {
      console.log(`未能连接服务器！将重试连接服务器。`)
    }
    // 重新启动websocket连接
    wx.start()
  })
  .on('open', async () => {
    let ret
    console.log('连接成功!')
    connected = true

    // 非首次登录时最好使用以前成功登录时使用的设备参数，
    // 否则可能会被tx服务器怀疑账号被盗，导致手机端被登出
    ret = await wx.init()
    if (!ret.success) {
      console.log('新建任务失败！', ret)
      return
    }
    console.log('新建任务成功, json: ', ret)

    //先尝试使用断线重连方式登陆
    if (autoData.token) {
      ret = await wx.login('token', autoData)
      if (ret.success) {
        console.log('断线重连请求成功！', ret)
        return
      }
      console.log('断线重连请求失败！', ret)

      ret = await wx.login('request', autoData)
      if (ret.success) {
        console.log('自动登录请求成功！', ret)
        return
      }
      console.log('自动登录请求失败！', ret)
    }

    ret = await wx.login('qrcode')
    if (!ret.success) {
      console.log('使用qrcode登录模式失败！', ret)
      return
    }
    console.log('使用qrcode登录模式！')
  })
  .on('qrcode', data => {
    // 如果存在url，则直接在终端中生成二维码并显示
    if (data.url) {
      console.log(`登陆二维码内容为: "${data.url}"，请使用微信扫描下方二维码登陆!`)
      qrcode.generate(data.url, { small: false })
    } else {
      console.log(`未能获得登陆二维码!`)
    }
  })
  .on('scan', data => {
    switch (data.status) {
      case 0:
        console.log('等待扫码...', data)
        break;
      case 1:
        console.log('已扫码，请在手机端确认登陆...', data)
        break;
      case 2:
        switch (data.subStatus) {
          case 0:
            console.log('扫码成功！登陆成功！', data)
            break;
          case 1:
            console.log('扫码成功！登陆失败！', data)
            break;
          default:
            console.log('扫码成功！未知状态码！', data)
            break;
        }
        break;
      case 3:
        console.log('二维码已过期！请重新调用登陆接口！', data)
        break;
      case 4:
        console.log('手机端已取消登陆！请重新调用登陆接口！', data)
        break;
      default:
        console.log('未知登陆状态！请重新调用登陆接口！', data)
        break;
    }
  })
  .on('login', async () => {
    console.log('微信账号登陆成功！')
    let ret

    ret = await wx.getMyInfo()
    console.log('当前账号信息：', ret.data)

    // 主动同步通讯录
    await wx.syncContact()

    if (!autoData.wxData) {
      // 如果已经存在设备参数，可不再获取
      ret = await wx.getWxData()
      if (!ret.success) {
        console.log('获取设备参数未成功！ json:', ret)
        return
      }
      console.log('获取设备参数成功, json: ', ret)
      Object.assign(autoData, { wxData: ret.data.wxData })
    }

    ret = await wx.getLoginToken()
    if (!ret.success) {
      console.log('获取自动登陆数据未成功！ json:', ret)
      return
    }
    console.log('获取自动登陆数据成功, json: ', ret)
    Object.assign(autoData, { token: ret.data.token })

    // NOTE: 这里将设备参数保存到本地，以后再次登录此账号时提供相同参数
    fs.writeFileSync('./config.json', JSON.stringify(autoData, null, 2))
    console.log('设备参数已写入到 ./config.json文件')
  })
  .on('logout', ({ msg }) => {
    console.log('微信账号已退出！', msg)
  })
  .on('loaded', async () => {
    console.log('通讯录同步完毕！')
      const users = 
      [ 'rana912',
      'F123094899',
      'yunixiangy3130']
     const room = await wx.createRoom(users)
     console.log(room)
     console.log('创建完毕')
      await delay(8000)
      const ret = await wx.sendMsg('filehelper', '你登录了！')
      console.log('发送信息结果：', ret)
      console.log('创建完毕222')
  })
  .on('push', async data => {
    if (data.mType == 2) {
      let notUsers = ['weibo', 'qqmail', 'tmessage', 'mmpaynotify', 'qmessage', 'floatbottle', 'medianote', 'fmessage', 'filehelper']
      if (!data.userName.startsWith('gh_') && !notUsers.includes(data.userName) && data.chatroomId == 0 && data.intro == '') {
        userList.push(data)
        userCount++
        //console.log(userCount++)
        // console.log(data)
        if (data.sex == 0) {
          console.log('收到推送联系人：%s - %s', data.userName, data.nickName)
        }
      }
    }
  })
  .on('error', e => {
    console.log('ws 错误:', e.message)
  })
  .on('warn', e => {
    console.log('任务出现错误:', e.message)
  })
`
建群代码

**Comment by leebo** [comment]
```
....忽略前面的log
收到推送联系人：wxid_7a0k01vf74ny22 - 随心🍎
通讯录同步完毕！
{ success: true,
  data:
   { message: 'Everything is OK',
     status: 0,
     userName: '5007668916@chatroom' } }
创建完毕
任务出现错误: 服务器返回错误提示：接收推送信息异常！
任务出现错误: 服务器返回错误提示：接收推送信息异常！
任务出现错误: 服务器返回错误提示：接收推送信息异常！
任务出现错误: 服务器返回错误提示：接收推送信息异常！
```

**Comment by binsee** [comment]
未能复现

请运行demo，然后使用其他号给机器人号发如下指令建群，然后查看是否出现推送异常。
如果必然出现，则换号测试。

```
#createRoom
[ "rana912","F123094899","yunixiangy3130"]
```

**Comment by binsee** [comment]
某些账号有不同的触发阈值，有的账号某些操作一切正常，有的账号会相对容易掉线。
所以尝试更换不同注册时间、不同好友数量、不同好友质量等条件的账号测试。尤其需要注意账号实名+绑银行卡，这类账号相对阈值会高一些，更稳定。

易触发推送异常的问题，在优化计划中，近期更新

**Comment by leebo** [comment]
好的非常感谢 好像是号的问题 我这边换个号再试试

**Comment by binsee** [comment]
请切换至新版本，新版本中应当不会出现此问题。
