### ISSUE TITLE
v0.6调用getLoginToken指令失败

### ISSUE THREAD

**Issue by ChandlerBent** [binsee/padchat-sdk#69]
request: ```{"cmd": "getLoginToken", "type": "user", "cmdId": "4"}```
response: ```{'type': 'cmdRet', 'cmdId': '4', 'taskId': '99BBDEBA-DFF8-FC5D-DACB-BE480B051840', 'payload': {}}```

已登录状态

**Comment by binsee** [comment]
ws通讯数据格式错误，已经解决
