### ISSUE TITLE
demo.js中loaded的使用

### ISSUE THREAD

**Issue by kuifu** [binsee/padchat-sdk#73]
.on('loaded', async () => {
    logger.info('通讯录同步完毕！')

    // 主动触发同步消息
    await wx.syncMsg()

    const ret = await wx.sendMsg('filehelper', '你登录了！')
    logger.info('发送信息结果：', ret)
  })

不是说新版中loaded为客户端自己判断吗？这段代码意思是服务端推送了loaded事件？

**Comment by binsee** [comment]
loaded是指通讯录载入完毕。
在`login`事件即登陆成功后，调用了`syncContact()`来触发同步通讯录，然后同步完毕后会触发`loaded`事件。如果没有调用`syncContact()`且使用`wx.setSyncContact(false)`关闭了同步通讯录，则不会触发`loaded`事件。

```javascript
  .on('login', async () => {
    logger.info('微信账号登陆成功！')
    let ret

    ret = await wx.getMyInfo()
    logger.info('当前账号信息：', ret.data)

    // 如果不想同步通讯录信息，可关闭同步通讯录
    // await wx.setSyncContact(false)

    // 主动同步通讯录
    await wx.syncContact()

    await saveAutoData()
  })
```

`syncContact()`接口只是触发一次同步通讯录，同步结果在`push`事件中下发。
单次同步同步不完整个通讯录，因此需要在`push`事件中判断通讯录是否同步完毕。如果同步完毕，则后续下发的通讯录是增量同步。

**Comment by kuifu** [comment]
我这里断线重连模式，执行了一次syncContact(), 收到了 push 过来的消息，的确包括联系人。
但是并没后收到loaded事件，为什么？

**Comment by kuifu** [comment]
{
  "type": "userEvent",
  "event": "push",
  "taskId": "A1A5FBA4-DAEA-E0BB-4FAD-4B8E52B6766B",
  "payload": {
    "list": [
      {
        "continue": 1,
        "msg_type": 2048,
        "status": 1,
        "uin": 3631588077
      },
      {
        "big_head": "http:\/\/wx.qlogo.cn\/mmhead\/ver_1\/GUwukmKWyylTDMaHaI6VvicOq525ibgncyOQCBb8zBJPc077VJQaiaX5R28XYBazpe8lrfqpbJcibmAPreZLBorjoA\/0",
        "bit_mask": 4294967295,
        "bit_value": 1,
        "chatroom_id": 0,
        "chatroom_owner": "",
        "city": "",
        "continue": 1,
        "country": "",
        "id": 0,
        "img_flag": 2,
        "intro": "",
        "label": "",
        "level": 9,
        "max_member_count": 0,
        "member_count": 0,
        "msg_type": 2,
        "nick_name": "语音记事本",
        "provincia": "",
        "py_initial": "YYJSB",

**Comment by kuifu** [comment]
另外，根据新版说明，联系人信息不是在contact事件里吗？为什么还是在push里？

**Comment by binsee** [comment]
https://github.com/binsee/padchat-sdk/issues/73#issuecomment-436153638

**Comment by binsee** [comment]
我在上边已经说明了，联系人推送是在websocket推送的push中，在本地解析后触发为push事件。

sdk的事件和websocket通讯的事件，并非完全一致。自行理解

**Comment by kuifu** [comment]
理解了，可以关闭。
