### ISSUE TITLE
为什么不同的是payload-type使用了相同的 taskid，而且还是重复。

### ISSUE THREAD

**Issue by kuifu** [binsee/padchat-sdk#74]
[DEBUG][2018-11-06 15:13:51]:-**-:{"type":"userEvent","event":"notify","taskId":"ED74905E-581F-4EBC-E7BC-A9AFBF0C2ED6","payload":{"type":2}}
[INFO][2018-11-06 15:13:51]:ws_message_handle():user event----------
[DEBUG][2018-11-06 15:13:51]:-**-:{"type":"userEvent","event":"notify","taskId":"ED74905E-581F-4EBC-E7BC-A9AFBF0C2ED6","payload":{"type":2}}
[INFO][2018-11-06 15:13:51]:ws_message_handle():user event----------
[DEBUG][2018-11-06 15:13:52]:-**-:{"type":"userEvent","event":"notify","taskId":"ED74905E-581F-4EBC-E7BC-A9AFBF0C2ED6","payload":{"type":2}}
[INFO][2018-11-06 15:13:52]:ws_message_handle():user event----------
[DEBUG][2018-11-06 15:13:52]:-**-:{"type":"userEvent","event":"notify","taskId":"ED74905E-581F-4EBC-E7BC-A9AFBF0C2ED6","payload":{"type":4}}
[INFO][2018-11-06 15:13:52]:ws_message_handle():user event----------
[DEBUG][2018-11-06 15:13:52]:-**-:{"type":"userEvent","event":"notify","taskId":"ED74905E-581F-4EBC-E7BC-A9AFBF0C2ED6","payload":{"type":2}}
[INFO][2018-11-06 15:13:52]:ws_message_handle():user event----------
[DEBUG][2018-11-06 15:13:53]:-**-:{"type":"userEvent","event":"notify","taskId":"ED74905E-581F-4EBC-E7BC-A9AFBF0C2ED6","payload":{"type":4}}

这是我自己程序获取到的服务端信息，为什么ED74905E-581F-4EBC-E7BC-A9AFBF0C2ED6多次出现？老版本也经常遇到，一直没搞明白。

**Comment by binsee** [comment]
taskId是服务端的任务id，无需关注

**Comment by kuifu** [comment]
看来不能通过这个 ID 做一些去重工作了。
