### ISSUE TITLE
发送朋友圈图片消息格式是否有错误

### ISSUE THREAD

**Issue by lvhy** [binsee/padchat-sdk#79]
`<TimelineObject>
    <contentDesc>123333</contentDesc>
    <contentDescShowType>1</contentDescShowType>
    <contentDescScene>0</contentDescScene>
    <private>3</private>
    <sightFolded>0</sightFolded>
    <appInfo>
        <id/>
        <version/>
        <appName/>
        <installUrl/>
        <fromUrl/>
        <isForceUpdate>0</isForceUpdate>
    </appInfo>
    <sourceUserName/>
    <sourceNickName/>
    <statisticsData/>
    <statExtStr/>
    <ContentObject>
        <contentStyle>1</contentStyle>
        <title/>
        <description/>
        <mediaList>
            <media>
                <type>2</type>
                <title/>
                <description>123333</description>
                <private>0</private>
                <userData/>
                <subType>0</subType>
                <url type="1" videomd5="">http://mmsns.qpic.cn/mmsns/PiajxSqBRaEKEWXbibq9UNnYGE1g6CnicS6g5YB8P3mLcekEwl0JrrCTex3qJGCZbhQ/0</url>
                <thumb type="1">http://mmsns.qpic.cn/mmsns/PiajxSqBRaEKEWXbibq9UNnYGE1g6CnicS6g5YB8P3mLcekEwl0JrrCTex3qJGCZbhQ/150</thumb>
            </media>
        </mediaList>
        <contentUrl/>
    </ContentObject>
    <actionInfo>
        <appMsg>
            <messageAction/>
        </appMsg>
    </actionInfo>
    <location poiClassifyId="" poiName="" poiAddress="" poiClassifyType="0" city=""/>
    <publicUserName/>
    <streamvideo>
        <streamvideourl/>
        <streamvideothumburl/>
        <streamvideoweburl/>
    </streamvideo>
</TimelineObject>`

**Comment by binsee** [comment]
见 #102
