### ISSUE TITLE
关于抄袭项目的警告！

### ISSUE THREAD

**Issue by binsee** [binsee/padchat-sdk#84]
目前发现有人抄袭本项目，完全复制本项目代码抄袭使用，登陆为`MAC`版微信。

在此特别声明，那些是抄袭项目！与本项目无关！
使用上遇到各种坑的，别到这里说，也与本项目无关！
使用非本项目遇到被封号、各种问题，不代表本项目会出现此问题！本项目不背锅！

尤其是涉及到金钱、敏感操作类，导致被封号的，与本项目无关！

使用其他项目导致账号或问题的，后果自负。

最后，得说一句，抄袭得真够无耻，也真够懒的。

**Comment by xinbenlv** [comment]
真的...而且有版权问题

**Comment by didikeke** [comment]
这个项目的license是？

**Comment by xinbenlv** [comment]
好像据我了解没有 License，默认就是All rights reserved 哈哈

Echo <notifications@github.com>于2019年1月4日 周五23:33写道：

**Comment by tianlu1677** [comment]
服务器url，后缀你的token：ws://127.0.0.1:7777/{YourToken} 如：ws://127.0.0.1:7777/mytoken_123456

怎么获取这个token，和wechaty一样？

**Comment by binsee** [comment]
@tianlu1677 和wechaty的token不同，属于两个不同项目。请向商务人员说明要用哪个接入

**Comment by ghost** [comment]
不是没有公布代码吗?怎么会有抄袭？
