### ISSUE TITLE
【同步联系人】只能触发一次contact事件

### ISSUE THREAD

**Issue by Hunk-zhurui** [binsee/padchat-sdk#85]
登录成功后同步联系人能收到推送联系人信息，后续再手动调用syncContact不会再触发contact事件

**Comment by Hunk-zhurui** [comment]
其他进群、离群推送信息能收到，就syncContact收不到推送

**Comment by Hunk-zhurui** [comment]
@binsee @lijiarui 什么时候能给给个说明

**Comment by binsee** [comment]
登陆成功后 syncContact 会同步到全量通讯录，触发`loaded`事件表示通讯录已经载入完毕
后续再调用`syncContact`时，因为通讯录没有变化，不会触发`contact`事件。
而当进群、离群、加好友等情况，通讯录会变化，会再收到`contact`事件
