### ISSUE TITLE
机器人主动邀请人进群，未收到type=10000的推送消息。

### ISSUE THREAD

**Issue by Hunk-zhurui** [binsee/padchat-sdk#86]
群已经存在了，机器人不是群主
然后机器人邀请新人进群
手机端有消息（你邀请xxx加入群聊）
手机端群信息自动更新了，成员数量也变化了
群内其他成员邀请人进群有通知事件，就机器人自己邀请人进群没有

**Comment by binsee** [comment]
某些系统消息当前可能收不到，后续会更新服务端解决

**Comment by Hunk-zhurui** [comment]
刚才用node 的 sdk 测试邀请人进群，居然收到了 type = 10002 的撤回消息，里面的内容又是邀请进群的消息
