### ISSUE TITLE
咨询下二次免扫码登录的问题

### ISSUE THREAD

**Issue by altheran2018** [binsee/padchat-sdk#87]
命令行中初次运行node demo，登录成功后，config.json也保存了wxdata数据，退出命令行后，下次再次运行项目node demo，还是需要扫码登录，请问下如何操作，下次可以通过wxdata数据免扫码登录？

**Comment by altheran2018** [comment]
[2018-11-29T10:31:48.424] [WARN] app - 自动登录请求失败！ { success: false,
  data: { message: '', status: -2017 },
  error: '登陆失败！' }

**Comment by binsee** [comment]
需要有wxdata和token数据。
需要注意两种免扫码登陆方式的区别
`auto`是断线重连，短时间内重连。如果手机端退出ipad登陆或断开机器人一定时间则会失效
`request`是二次登陆，token可长时间有效。手机端会弹出登陆确认界面，需要点按钮后才会登陆
