### ISSUE TITLE
登录异常

### ISSUE THREAD

**Issue by cyyuen** [binsee/padchat-sdk#91]
连续使用断线重连，自动登录，二维码登录失败。昨天还可以成功登录，今天不知道为什么不行了。

log as following:

^[[32m[2019-02-06T14:13:31.700] [INFO] app - ^[[39m当前连接接口服务器为： ws://padchat-sdk.botorange.com:8989/code
^[[32m[2019-02-06T14:13:32.125] [INFO] app - ^[[39m连接成功!
^[[32m[2019-02-06T14:13:32.186] [INFO] app - ^[[39m新建任务成功, json:  { success: true, data: {} }
^[[32m[2019-02-06T14:13:32.188] [INFO] app - ^[[39mtrying to 断线重连...
^[[33m[2019-02-06T14:18:32.778] [WARN] app - ^[[39m断线重连请求失败！ { success: false,
  data: { message: '', status: 0 },
  error: '接口未返回有效数据' }
^[[32m[2019-02-06T14:18:32.779] [INFO] app - ^[[39mtrying to 自动登录...
^[[33m[2019-02-06T14:23:33.331] [WARN] app - ^[[39m自动登录请求失败！ { success: false,
  data: { message: '', status: 0 },
  error: '接口未返回有效数据' }
^[[91m[2019-02-06T14:28:33.924] [ERROR] app - ^[[39m未能获得登陆二维码!
^[[32m[2019-02-06T14:28:33.925] [INFO] app - ^[[39mtrying to qrcode登录...
^[[91m[2019-02-06T14:28:33.926] [ERROR] app - ^[[39m使用qrcode登录模式失败！ { success: false, data: {} }

**Comment by binsee** [comment]
已经处理，待后续观察。
